variable "ec2_security_group_name" {}
variable "vpc_id" {}
variable "ec2_security_group_desc" {}
variable "ec2_security_group_tag_val" {}
variable "ec2_security_group_http_proxy_desc" {}
variable "ec2_security_group_http_proxy_port" {}
variable "ec2_security_group_http_proxy_protocol" {}
variable "ec2_security_group_http_proxy_cidr" {}
variable "ec2_security_group_ssh_proxy_desc" {}
variable "ec2_security_group_ssh_proxy_port" {}
variable "ec2_security_group_ssh_proxy_protocol" {}
variable "ec2_security_group_ssh_proxy_cidr" {}
variable "ec2_security_group_egress_port" {}
variable "ec2_security_group_egrress_protocol" {}
variable "ec2_security_group_egress_cidr" {}
variable "default_az_id" {}
variable "jenkins_instance_profile_name" {}
variable "ec2_keypair_name" {}
variable "ec2_instanct_tag_val" {}